### ISSUE TITLE
Old jar version

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#1]
Hi!

I downloaded your jar file from the link you referred in the README but I noticed it has an older version (`1.3.0` instead of `1.4.0`).
I just noted this because might forgot updating it.

Best regards

**Comment by stephansann** [comment]
Hi Daniel
Thanks for this feedback.
Where did you find this outdated link?
I just checked both the project page and the website and all links to JAR files seem to point to the current version (1.4.0)!?
Best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi, 

The outdated jar was the windows jar but I checked it now and it's the right one :)
Maybe I read the README of a previous commit somehow or I don't know.

Thank you
