### ISSUE TITLE
Always have the option to open the file in external editor

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#10]
If a file-type is supported by Document Archiver, it displays it in an internal view. And that's totally fine. 

My suggestion is that there should be some button or control for opening the file in an external editor too ( it would be useful for example if the `docx` preview is not enough and I want to quickly open it in the external editor).

It's just a representation:
![image](https://user-images.githubusercontent.com/49782833/115353640-0cc21600-a1b9-11eb-8ea1-51af237202ec.png)

What do you think?

**Comment by stephansann** [comment]
That would definitely a good functionality. Going to implement that in short. Thanks als always 🙏🏻

**Comment by stephansann** [comment]
Done 😊

Please find it in the newest SNAPSHOT build:
https://repository.sophisticatedapps.com/snapshots/com/sophisticatedapps/archiving/document-archiver/1.6.0-SNAPSHOT

Thanks again for the suggestion.
