### ISSUE TITLE
Using radio menu items for themes & languagges

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#11]
If I look at the theme/language selection, I can't see what is currently configured:

![menu items currently](https://user-images.githubusercontent.com/49782833/115354892-6bd45a80-a1ba-11eb-9af6-1616516f60fd.png)

So, my suggestion is that use `RadioMenuItem`s instead of regular `MenuItem`s.
Here is an example:
![example](https://user-images.githubusercontent.com/49782833/115355549-10569c80-a1bb-11eb-841e-3eb6a4985aa8.png)

So the user can see what is the currently configured option.

**Comment by stephansann** [comment]
Yes, same is true for the languages. Will be the next thing on my list. Shouldn't be so hard to do 😊

**Comment by stephansann** [comment]
Voilà! Please find it in the newest SNAPSHOT build:
https://repository.sophisticatedapps.com/snapshots/com/sophisticatedapps/archiving/document-archiver/1.6.0-SNAPSHOT

Thanks again for the good input! 🙏🏻
