### ISSUE TITLE
Drag n drop support

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#12]
It would be great to have the ability to drag files/directories from the file-explorer:
![drgndrop](https://user-images.githubusercontent.com/49782833/115356997-77288580-a1bc-11eb-8493-f261665d34f4.gif)

It's basically the same if I open files/directories with the help of the `MenuBar` but sometimes the drag n drop is more comfortable.

**Comment by stephansann** [comment]
Man - you are a good-ideas-machine! 😀

Will also go to my TODO list. Thanks as always.

**Comment by stephansann** [comment]
Done 😊

You can now use drag-n-drop after canceling the file-/folder-open-dialog, or by dragging files and/or folders on the "Documents Pane":

https://repository.sophisticatedapps.com/snapshots/com/sophisticatedapps/archiving/document-archiver/2.1.0-SNAPSHOT/document-archiver-2.1.0-20210514.171018-6-linux.zip

Also tried to add drag-n-drop support to the "Display File Pane", but that only works in part. If for example an image is displayed it works, but with a PDF being displayed it doesn't work (maybe the author of PDFViewerFX could do something about it 😉).
Anyhow removed it there for consistency.

HTH.

Best regards
Stephan
