### ISSUE TITLE
Ability to archive URLs

### ISSUE THREAD

**Issue by kia0007** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#19]

**Comment by stephansann** [comment]
Hi @kia0007 

Thanks for the suggestion.

Document Archiver aims to archive files, not information snippets.

Anyhow what you can do is save an URL in an .url-file like this:

```
[InternetShortcut]
URL=https://document-archiver.github.io/
```

This file you can archive with Document Archiver like any other file.

Best regards
Stephan

**Comment by kia0007** [comment]
I was thinking that maybe you could add a future like when you are archiving a picture, there is an empty bar in the software where you can add various things like a link or a sentence and the software will add a white space to the picture and then write them there. maybe even adding an OCR feature to the archive browser that can read those links

**Comment by stephansann** [comment]
Thanks for the further suggestions. Anyhow those kind of advanced image manipulation features are outside the scope of DocumentArchiver.
