### ISSUE TITLE
Markdown file (.md) support

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#2]
Hi ,

I noticed that markdown (.md) files are not supported by Document Archiver yet.

![screenshot](https://user-images.githubusercontent.com/49782833/114836096-94331200-9dd2-11eb-9954-887221ad16d0.png)

You can implement markdown support with the help of this library called [MarkdownEditorControlFX](https://github.com/Dansoftowner/MarkdownEditorControlFX) that provides a JavaFX control for previewing/editing markdown. 

![MarkdownEditorControlFX demo](https://user-images.githubusercontent.com/49782833/114837528-196af680-9dd4-11eb-9e57-4a90bd92275f.png)

You can disable the editing by:
```java
MarkdownEditorControl control = new MarkdownEditorControl();
control.setEditable(false);
```

Hope you find this enhancement request useful! :)
Best regards!

**Comment by stephansann** [comment]
Hi Daniel

This is indeed a brilliant tip 😀

Wow - another cool library by you 👍🏻

I will definitely include this in Document Archiver.

Best regards
Stephan

**Comment by stephansann** [comment]
Hi again

Just added the dependency to my project and found that this will add 2.5 MB of half-baked sub-dependencies:

<img width="653" alt="Screen Shot 2021-04-15 at 16 34 33" src="https://user-images.githubusercontent.com/9678681/114887736-ff97d680-9e08-11eb-9e62-74fa00844244.png">

Came to the conclusion that the cost(risk)/advantage ratio is not right here for one single filetype which is not really /so/ important for archiving (would be different for .docx-files (for which I am still searching for a solution)). I will just add Markdown files now to be displayed as plain text (should be okay for everybody dealing with Markdown files).

Maybe if there would be a more lightweight viewing-only library in the future (*wink*) I would give it a second thought.

Best regards
Stephan

**Comment by Dansoftowner** [comment]
Yeah, that's totally fine, no problem. I just suggested it as a "bonus" feature you know :)
