### ISSUE TITLE
Updating `jSystemThemeDetector` to version `3.0` for modularity support

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#4]
You [mentioned](https://github.com/Document-Archiver/com.sophisticatedapps.archiving.document-archiver/issues/3#issuecomment-820296129) that it would be great to have modularity in `jSystemthemeDetector` so now I [released](https://github.com/Dansoftowner/jSystemThemeDetector/releases/tag/3.0) a new version that provides it.

The module name is `com.jthemedetector` :)

**Comment by stephansann** [comment]
Great! 👍🏻
Will include that version in the next release of Document Archiver.
Thanks for the amazing work!

**Comment by stephansann** [comment]
Included for version 1.5.0.
