### ISSUE TITLE
Ideas for implementing Word document (`.docx`) support

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#5]
Hi!

You [mentioned](https://github.com/Document-Archiver/com.sophisticatedapps.archiving.document-archiver/issues/2#issuecomment-820487308) in a previous issue that you are searching for a Word document displaying solution.

I can give you some thoughts on it :)

So, a word document can be converted to HTML. If you find a good 'docx to html' converter library, you can easily display the
HTML in a JavaFX `WebView`.

Some sites that can be helpful:
* [Convert Word doc to HTML programmatically in Java](https://stackoverflow.com/questions/227236/convert-word-doc-to-html-programmatically-in-java)
 * [Word Document (DOC/DOCX) to HTML Conversion using Java](https://blog.aspose.com/2020/07/15/word-document-doc-docx-to-html-conversion-using-java/)
 * [java-mammoth - Convert Word documents to simple and clean HTML](https://github.com/mwilliamson/java-mammoth)
 * [Apache POI - WordToHtmlConverter](https://poi.apache.org/apidocs/dev/org/apache/poi/hwpf/converter/WordToHtmlConverter.html)
 
Another solution can be a 'Word to image' converter library, and then display the images below each other (but that has a lot of disadvantages).

Hope it helps you moving forward!

Best regards
Daniel

**Comment by stephansann** [comment]
Hi Daniel
Thank you very much for the links.
A few of them I already saw. The others I will read soon.
I already had different ideas, like converting .docx-files into PDF. Problem is the most libraries I found were either commercial or terribly outdated / not maintained any more.
Anyhow I will have a second look at the "to HTML" approach.
Thanks again and best regards
Stephan

**Comment by stephansann** [comment]
Added the Mammoth converter in version 1.5. Thanks again for the suggestion 🙏🏻

**Comment by Dansoftowner** [comment]
Wow, nice job! @stephansann
