### ISSUE TITLE
Some content doesn't fit to window

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#8]
Hi @stephansann ,

I have a little problem on Windows:

![image](https://user-images.githubusercontent.com/49782833/115140381-48cd6d80-a037-11eb-85ed-5159eec9959c.png)
 
You can see that some content are "cropped" on the right side.

Maybe you could have a look at this.

Best regards
Daniel

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Yes, thanks - I already saw that. Only happens on Windows - on Mac and Linux it's fine.

Since the widths of the TextFields are not hard set (should be calculated by JavaFX), I could imagine this is a bug in the Windows-Implementation of JavaFX. I'll have to dig a bit deeper here.

**Comment by stephansann** [comment]
Hi @Dansoftowner 

I took a closer look and it seems there's really a bug in JavaFX on Windows. The stage width will be reported 16 pixel wider than it is. Even in full screen the stage is 16 pixel wider than the screen has pixels 🤪

Ich dealt with in in my code and it should be okay in the newest SNAPSHOT version.

Could you please have a look?

https://repository.sophisticatedapps.com/snapshots/com/sophisticatedapps/archiving/document-archiver/1.6.0-SNAPSHOT/document-archiver-1.6.0-20210419.220025-3-win.jar

**Comment by Dansoftowner** [comment]
Okay, It's good now :)

![image](https://user-images.githubusercontent.com/49782833/115350957-02524d00-a1b6-11eb-8f01-914f12d6ac54.png)
